import AppKit
import UniformTypeIdentifiers

private final class StudioResizeHandle: NSView {
    enum Axis { case horizontal, vertical }
    let axis: Axis; var dragged: ((CGFloat) -> Void)?; private var lastPoint: NSPoint?
    init(axis: Axis) { self.axis = axis; super.init(frame: .zero); wantsLayer = true }
    required init?(coder: NSCoder) { fatalError() }
    override func resetCursorRects() { addCursorRect(bounds, cursor: axis == .vertical ? .resizeLeftRight : .resizeUpDown) }
    override func mouseDown(with event: NSEvent) { lastPoint = event.locationInWindow }
    override func mouseDragged(with event: NSEvent) { guard let p = lastPoint else { return }; let n = event.locationInWindow; let d = axis == .vertical ? n.x-p.x : n.y-p.y; lastPoint=n; dragged?(d) }
}
private final class StudioLayoutState { static let shared=StudioLayoutState(); var leftWidth:CGFloat=330; var rightWidth:CGFloat=350; var arrangementFraction:CGFloat=0.58; weak var leftHandle:StudioResizeHandle?; weak var rightHandle:StudioResizeHandle?; weak var horizontalHandle:StudioResizeHandle? }

private final class LiveArrangementView: NSView {
    var tracks:[EngineTrack]=[]; var clips:[EngineClip]=[]; var selectedTrackID:Int?; var selectedClipID:Int?; var onSelectTrack:((Int)->Void)?; var onSelectClip:((Int,Int)->Void)?
    private let colors:[NSColor] = [.systemBlue,.systemRed,.systemGreen,.systemOrange,.systemPurple,.systemTeal,.systemGray]
    override var isFlipped:Bool { true }
    override func draw(_ dirtyRect:NSRect) {
        NSColor.csArrangement.setFill(); bounds.fill(); let header:CGFloat=170, top:CGFloat=58
        NSColor.csPanelStrong.setFill(); NSRect(x:0,y:0,width:header,height:bounds.height).fill(); NSColor.csTop.setFill(); NSRect(x:header,y:0,width:max(0,bounds.width-header),height:top).fill()
        let maxBeat=max(16.0,clips.map{$0.startBeat+$0.lengthBeats}.max() ?? 16.0), beatW=max(8,(bounds.width-header-12)/CGFloat(maxBeat))
        let sections=["A – Einführung","B – Entwicklung","C – Höhepunkt","D – Ausklang"]
        let sectionColors=[NSColor.systemGreen.withAlphaComponent(0.18),NSColor.systemBlue.withAlphaComponent(0.16),NSColor.systemRed.withAlphaComponent(0.15),NSColor.systemPurple.withAlphaComponent(0.15)]
        for i in 0..<4 { let x=header+CGFloat(i)*(bounds.width-header)/4; let w=(bounds.width-header)/4; sectionColors[i].setFill(); NSRect(x:x,y:24,width:w,height:34).fill(); (sections[i] as NSString).draw(in:NSRect(x:x+4,y:34,width:w-8,height:16),withAttributes:[.font:NSFont.systemFont(ofSize:11,weight:.medium),.foregroundColor:NSColor.csText]) }
        for b in stride(from:0,through:Int(ceil(maxBeat)),by:4) { let x=header+CGFloat(b)*beatW; NSColor.csLine.setStroke(); let p=NSBezierPath(); p.move(to:NSPoint(x:x,y:top)); p.line(to:NSPoint(x:x,y:bounds.height)); p.stroke(); ("\(b+1)" as NSString).draw(at:NSPoint(x:x+3,y:6),withAttributes:[.font:NSFont.systemFont(ofSize:10),.foregroundColor:NSColor.secondaryLabelColor]) }
        let n=max(1,tracks.count), rowH=max(52,(bounds.height-top)/CGFloat(n))
        for (i,t) in tracks.enumerated() { let y=top+CGFloat(i)*rowH, c=colors[i%colors.count]; (t.id==selectedTrackID ? NSColor.selectedContentBackgroundColor.withAlphaComponent(0.12):NSColor.csPanelStrong).setFill(); NSRect(x:0,y:y,width:header,height:rowH).fill(); c.setFill(); NSBezierPath(roundedRect:NSRect(x:8,y:y+8,width:16,height:max(24,rowH-16)),xRadius:3,yRadius:3).fill(); ("\(i+1)" as NSString).draw(in:NSRect(x:9,y:y+18,width:14,height:14),withAttributes:[.font:NSFont.systemFont(ofSize:10,weight:.bold),.foregroundColor:NSColor.white]); (t.name as NSString).draw(in:NSRect(x:33,y:y+9,width:128,height:18),withAttributes:[.font:NSFont.systemFont(ofSize:13,weight:.semibold),.foregroundColor:NSColor.csText]); ("M    S    ●" as NSString).draw(in:NSRect(x:33,y:y+31,width:100,height:16),withAttributes:[.font:NSFont.systemFont(ofSize:11),.foregroundColor:NSColor.secondaryLabelColor]); NSColor.csLine.setStroke(); let l=NSBezierPath(); l.move(to:NSPoint(x:0,y:y+rowH)); l.line(to:NSPoint(x:bounds.width,y:y+rowH)); l.stroke()
            for clip in clips where clip.trackId==t.id { let x=header+CGFloat(clip.startBeat)*beatW, w=max(12,CGFloat(clip.lengthBeats)*beatW), r=NSRect(x:x,y:y+8,width:min(w,max(4,bounds.width-x-4)),height:max(20,rowH-16)); c.withAlphaComponent(clip.id==selectedClipID ? 0.30:0.18).setFill(); NSBezierPath(roundedRect:r,xRadius:5,yRadius:5).fill(); if clip.id==selectedClipID { c.setStroke(); let q=NSBezierPath(roundedRect:r,xRadius:5,yRadius:5); q.lineWidth=2; q.stroke() }; for note in clip.notes.prefix(500) { let nx=x+CGFloat(note.startBeat)*beatW, nw=max(2,CGFloat(note.lengthBeats)*beatW), pitch=CGFloat(127-note.note)/127, ny=r.minY+4+pitch*max(1,r.height-10); c.setFill(); NSRect(x:nx,y:ny,width:min(nw,max(1,r.maxX-nx)),height:2).fill() } }
        }
        if tracks.isEmpty { ("Noch keine Spur – MIDI importieren oder + drücken" as NSString).draw(in:NSRect(x:header+24,y:top+28,width:430,height:28),withAttributes:[.font:NSFont.systemFont(ofSize:15,weight:.medium),.foregroundColor:NSColor.secondaryLabelColor]) }
    }
    override func mouseDown(with event:NSEvent) { let p=convert(event.locationInWindow,from:nil), header:CGFloat=170, top:CGFloat=58; guard p.y>=top,!tracks.isEmpty else{return}; let rowH=max(52,(bounds.height-top)/CGFloat(max(1,tracks.count))), i=min(tracks.count-1,max(0,Int((p.y-top)/rowH))), t=tracks[i]; selectedTrackID=t.id; if p.x>header { let maxBeat=max(16.0,clips.map{$0.startBeat+$0.lengthBeats}.max() ?? 16.0), beatW=max(8,(bounds.width-header-12)/CGFloat(maxBeat)), beat=Double((p.x-header)/beatW); if let c=clips.first(where:{$0.trackId==t.id && beat >= $0.startBeat && beat <= $0.startBeat+$0.lengthBeats}) { selectedClipID=c.id; onSelectClip?(t.id,c.id) } }; onSelectTrack?(t.id); needsDisplay=true }
}

private final class LivePianoRollView:NSView {
    var notes:[EngineMidiNote]=[]; var title="Keine MIDI-Auswahl"; override var isFlipped:Bool { true }
    override func draw(_ dirtyRect:NSRect) { NSColor.csEditor.setFill(); bounds.fill(); (title as NSString).draw(at:NSPoint(x:10,y:7),withAttributes:[.font:NSFont.systemFont(ofSize:13,weight:.semibold),.foregroundColor:NSColor.csText]); guard !notes.isEmpty else { ("Clip auswählen, um seine echten MIDI-Noten zu sehen" as NSString).draw(at:NSPoint(x:60,y:48),withAttributes:[.font:NSFont.systemFont(ofSize:13),.foregroundColor:NSColor.secondaryLabelColor]); return }; let minN=notes.map{$0.note}.min()!, maxN=notes.map{$0.note}.max()!, span=max(12,maxN-minN+1), maxBeat=max(4.0,notes.map{$0.startBeat+$0.lengthBeats}.max() ?? 4.0), left:CGFloat=48, top:CGFloat=30, bw=max(8,(bounds.width-left-8)/CGFloat(maxBeat)), rh=max(4,(bounds.height-top-8)/CGFloat(span)); for b in 0...Int(ceil(maxBeat)) { let x=left+CGFloat(b)*bw; NSColor.csLine.withAlphaComponent(0.45).setStroke(); let p=NSBezierPath(); p.move(to:NSPoint(x:x,y:top)); p.line(to:NSPoint(x:x,y:bounds.height)); p.stroke() }; for n in notes { let x=left+CGFloat(n.startBeat)*bw,y=top+CGFloat(maxN-n.note)*rh,w=max(3,CGFloat(n.lengthBeats)*bw); NSColor.systemGreen.setFill(); NSBezierPath(roundedRect:NSRect(x:x,y:y,width:min(w,max(1,bounds.width-x-4)),height:max(3,rh-1)),xRadius:2,yRadius:2).fill() } }
}
private final class LiveStudioState { static let shared=LiveStudioState(); let arrangement=LiveArrangementView(); let piano=LivePianoRollView(); var selectedTrackID:Int?; var selectedClipID:Int?; var importButton:NSButton?; var installed=false }

extension StudioViewController {
    func installEngineBindings(engineReady:Bool) { playButton.target=self; playButton.action=#selector(enginePlayPause); stopButton.target=self; stopButton.action=#selector(engineStop); recordButton.target=self; recordButton.action=#selector(engineRecord); installReadableTypography(); installResizablePanes(); installLiveDAW(); if let f=transportCard.subviews.compactMap({$0 as? NSTextField}).first(where:{$0.identifier?.rawValue=="tempo"}) { f.isEditable=true; f.isSelectable=true; f.target=self; f.action=#selector(engineTempoChanged(_:)) }; if let b=transportCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.title.contains("Metronom")}) { b.target=self; b.action=#selector(engineMetronome(_:)) }; if let b=transportCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.identifier?.rawValue=="open"}) { b.target=self;b.action=#selector(engineOpenProject) }; if let b=transportCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.identifier?.rawValue=="save"}) { b.target=self;b.action=#selector(engineSaveProject) }; statusLabel.stringValue=engineReady ? "Bereit":"Audio-Engine Fehler"; refreshEngineUI() }
    private func installLiveDAW() { let s=LiveStudioState.shared; guard !s.installed else{return}; s.installed=true; arrangement.isHidden=true; pianoRoll.isHidden=true; arrangementCard.addSubview(s.arrangement); inspectorCard.addSubview(s.piano); s.arrangement.onSelectTrack={[weak self] id in s.selectedTrackID=id;self?.syncLiveDAW()}; s.arrangement.onSelectClip={[weak self] tid,cid in s.selectedTrackID=tid;s.selectedClipID=cid;self?.syncLiveDAW()}; if let plus=arrangementCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.identifier?.rawValue=="arrPlus"}) { plus.target=self;plus.action=#selector(engineAddTrack) }; if let minus=arrangementCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.identifier?.rawValue=="arrMinus"}) { minus.target=self;minus.action=#selector(engineRemoveTrack) }; let imp=NSButton(title:"MIDI importieren",target:self,action:#selector(engineImportMIDI));styleButton(imp,strong:true);arrangementCard.addSubview(imp);s.importButton=imp
        chatCard.isHidden=false; chatText.string="KI-Dialog wird erst wieder aktiviert, wenn die echte Modellanbindung angeschlossen ist."; chatText.isEditable=false; chatInput.isEnabled=false; sectionButtons.forEach{$0.isEnabled=false}; if let send=chatCard.subviews.compactMap({$0 as? NSButton}).first(where:{$0.identifier?.rawValue=="send"}) { send.isEnabled=false }
        browserList.subviews.forEach{$0.removeFromSuperview()}; browserTitle.stringValue="Plugins"; browserButtons.forEach{$0.isEnabled=false}; if let search=browserCard.subviews.compactMap({$0 as? NSSearchField}).first(where:{$0.identifier?.rawValue=="browserSearch"}) { search.isEnabled=false; search.placeholderString="Plugin-Anbindung folgt" }
        inspectorButtons.forEach{$0.isEnabled=false}; inspectorCard.subviews.filter{$0.identifier?.rawValue.hasPrefix("chain_")==true}.forEach{$0.isHidden=true}; inspectorCard.subviews.filter{$0.identifier?.rawValue.hasPrefix("editor_")==true}.forEach{$0.isHidden=false}; syncLiveDAW() }
    private func syncLiveDAW() { let e=CompositionStudioEngine.shared,s=LiveStudioState.shared;guard e.isReady else{return};let ts=e.tracks(),cs=e.clips();if s.selectedTrackID==nil || !ts.contains(where:{$0.id==s.selectedTrackID}){s.selectedTrackID=ts.first?.id};if s.selectedClipID != nil && !cs.contains(where:{$0.id==s.selectedClipID}){s.selectedClipID=nil};s.arrangement.tracks=ts;s.arrangement.clips=cs;s.arrangement.selectedTrackID=s.selectedTrackID;s.arrangement.selectedClipID=s.selectedClipID;s.arrangement.needsDisplay=true;if let t=ts.first(where:{$0.id==s.selectedTrackID}){inspectorTitle.stringValue="Spur: \(t.name)"}else{inspectorTitle.stringValue="Keine Spur"};if let c=cs.first(where:{$0.id==s.selectedClipID}){s.piano.notes=c.notes;s.piano.title="Pianoroll · \(c.notes.count) echte MIDI-Noten"}else{s.piano.notes=[];s.piano.title="Pianoroll"};s.piano.needsDisplay=true }
    @objc private func engineAddTrack(){let id=CompositionStudioEngine.shared.createTrack(name:"MIDI Spur \(CompositionStudioEngine.shared.tracks().count+1)");if id>=0{LiveStudioState.shared.selectedTrackID=id;statusLabel.stringValue="Spur angelegt"};syncLiveDAW()}
    @objc private func engineRemoveTrack(){guard let id=LiveStudioState.shared.selectedTrackID else{return};CompositionStudioEngine.shared.deleteTrack(id:id);LiveStudioState.shared.selectedTrackID=nil;LiveStudioState.shared.selectedClipID=nil;statusLabel.stringValue="Spur gelöscht";syncLiveDAW()}
    @objc private func engineImportMIDI(){let p=NSOpenPanel();p.allowedContentTypes=[.midi];p.allowsMultipleSelection=false;guard let w=view.window else{return};p.beginSheetModal(for:w){[weak self] r in guard r == .OK,let u=p.url,let self else{return};let target=LiveStudioState.shared.selectedTrackID ?? -1;let cid=CompositionStudioEngine.shared.importMIDI(path:u.path,trackId:target,startBeat:0);if cid>=0{let clips=CompositionStudioEngine.shared.clips();LiveStudioState.shared.selectedClipID=cid;LiveStudioState.shared.selectedTrackID=clips.first(where:{$0.id==cid})?.trackId;self.statusLabel.stringValue="MIDI importiert";self.syncLiveDAW()}else{self.statusLabel.stringValue="MIDI-Import fehlgeschlagen"}}}
    private func installReadableTypography(){func enlarge(_ r:NSView){for v in r.subviews{if let f=v as? NSTextField,let font=f.font{f.font=.systemFont(ofSize:max(font.pointSize+2,13))}else if let b=v as? NSButton{b.font=.systemFont(ofSize:13,weight:.medium)};enlarge(v)}};enlarge(view);timeLabel.font=.monospacedDigitSystemFont(ofSize:19,weight:.semibold);inspectorTitle.font=.systemFont(ofSize:15,weight:.bold);playButton.font=.systemFont(ofSize:20,weight:.bold);stopButton.font=.systemFont(ofSize:18,weight:.bold);recordButton.font=.systemFont(ofSize:20,weight:.bold)}
    private func installResizablePanes(){let s=StudioLayoutState.shared;guard s.leftHandle==nil else{return};let l=StudioResizeHandle(axis:.vertical),r=StudioResizeHandle(axis:.vertical),h=StudioResizeHandle(axis:.horizontal);view.addSubview(l);view.addSubview(r);view.addSubview(h);s.leftHandle=l;s.rightHandle=r;s.horizontalHandle=h;l.dragged={[weak self]d in s.leftWidth=min(520,max(280,s.leftWidth+d));self?.applyResizableLayout()};r.dragged={[weak self]d in s.rightWidth=min(520,max(290,s.rightWidth-d));self?.applyResizableLayout()};h.dragged={[weak self]d in guard let self else{return};let u=max(1,self.arrangementCard.frame.height+self.inspectorCard.frame.height);s.arrangementFraction=min(.78,max(.42,s.arrangementFraction+d/u));self.applyResizableLayout()}}
    private func applyResizableLayout(){let s=StudioLayoutState.shared,W=view.bounds.width,H=view.bounds.height,m:CGFloat=8,g:CGFloat=7,topH:CGFloat=50,trH:CGFloat=72,contentTop=m+topH+g,bottomY=H-m-trH;let leftW=min(s.leftWidth,W*.28),rightW=min(s.rightWidth,W*.28),centerX=m+leftW+g,centerW=max(520,W-2*m-leftW-rightW-2*g),centerH=max(400,bottomY-contentTop-g),arrH=max(250,min(centerH-190,centerH*s.arrangementFraction));topBar.frame=NSRect(x:m,y:m,width:W-2*m,height:topH);chatCard.frame=NSRect(x:m,y:contentTop,width:leftW,height:centerH);arrangementCard.frame=NSRect(x:centerX,y:contentTop,width:centerW,height:arrH);inspectorCard.frame=NSRect(x:centerX,y:contentTop+arrH+g,width:centerW,height:centerH-arrH-g);browserCard.frame=NSRect(x:centerX+centerW+g,y:contentTop,width:rightW,height:centerH);transportCard.frame=NSRect(x:m,y:bottomY,width:W-2*m,height:trH);s.leftHandle?.frame=NSRect(x:m+leftW-3,y:contentTop,width:10,height:centerH);s.rightHandle?.frame=NSRect(x:centerX+centerW-3,y:contentTop,width:10,height:centerH);s.horizontalHandle?.frame=NSRect(x:centerX,y:contentTop+arrH-3,width:centerW,height:10);layoutTop();layoutChat();layoutBrowser();layoutInspector();layoutTransport();let live=LiveStudioState.shared;live.arrangement.frame=NSRect(x:8,y:42,width:arrangementCard.bounds.width-16,height:arrangementCard.bounds.height-50);live.importButton?.frame=NSRect(x:14,y:9,width:126,height:30);live.piano.frame=NSRect(x:178,y:38,width:max(100,inspectorCard.bounds.width-190),height:max(70,inspectorCard.bounds.height-48));enlargeTransportControls()}
    private func enlargeTransportControls(){let w=transportCard.bounds.width,y:CGFloat=10;stopButton.frame=NSRect(x:w*.46-62,y:y,width:48,height:48);playButton.frame=NSRect(x:w*.46-5,y:y-3,width:54,height:54);recordButton.frame=NSRect(x:w*.46+58,y:y-3,width:54,height:54);timeLabel.frame=NSRect(x:w*.20,y:20,width:135,height:30);transportCard.subviews.first{$0.identifier?.rawValue=="open"}?.frame=NSRect(x:w-196,y:18,width:82,height:34);transportCard.subviews.first{$0.identifier?.rawValue=="save"}?.frame=NSRect(x:w-106,y:18,width:92,height:34)}
    func refreshEngineUI(){applyResizableLayout();let e=CompositionStudioEngine.shared;guard e.isReady else{return};playButton.title=e.isPlaying ? "❚❚":"▶";statusLabel.stringValue=e.isRecording ? "Aufnahme":(e.isPlaying ? "Wiedergabe":"Bereit");let x=max(0,e.positionSeconds),mi=Int(x)/60,se=Int(x)%60,ms=Int((x-floor(x))*1000);timeLabel.stringValue=String(format:"%02d:%02d.%03d",mi,se,ms);if let f=transportCard.subviews.compactMap({$0 as? NSTextField}).first(where:{$0.identifier?.rawValue=="tempo"}),f.currentEditor()==nil{f.stringValue=String(format:"Tempo\n%.2f",e.tempo)};syncLiveDAW()}
    @objc private func enginePlayPause(){let e=CompositionStudioEngine.shared;e.isPlaying ? e.pause():e.play();refreshEngineUI()}
    @objc private func engineStop(){let e=CompositionStudioEngine.shared;e.stop();e.locate(seconds:0);refreshEngineUI()}
    @objc private func engineRecord(){CompositionStudioEngine.shared.record();refreshEngineUI()}
    @objc private func engineTempoChanged(_ f:NSTextField){let s=f.stringValue.replacingOccurrences(of:"Tempo",with:"").replacingOccurrences(of:"\n",with:"").trimmingCharacters(in:.whitespacesAndNewlines).replacingOccurrences(of:",",with:".");if let v=Double(s){CompositionStudioEngine.shared.setTempo(v)};refreshEngineUI()}
    @objc private func engineMetronome(_ b:NSButton){let e=CompositionStudioEngine.shared;e.setMetronome(!e.isMetronomeEnabled);refreshEngineUI()}
    @objc private func engineSaveProject(){let p=NSSavePanel();if let t=UTType(filenameExtension:"mgd"){p.allowedContentTypes=[t]};p.nameFieldStringValue=model.projectName+".mgd";guard let w=view.window else{return};p.beginSheetModal(for:w){[weak self]r in guard r == .OK,let u=p.url,let self else{return};self.statusLabel.stringValue=CompositionStudioEngine.shared.saveProject(as:u.path) ? "Projekt gespeichert":"Speichern fehlgeschlagen"}}
    @objc private func engineOpenProject(){let p=NSOpenPanel();if let t=UTType(filenameExtension:"mgd"){p.allowedContentTypes=[t]};guard let w=view.window else{return};p.beginSheetModal(for:w){[weak self]r in guard r == .OK,let u=p.url,let self else{return};if CompositionStudioEngine.shared.loadProject(from:u.path){self.model.projectName=u.deletingPathExtension().lastPathComponent;self.projectLabel.stringValue="Projekt: \(self.model.projectName)";LiveStudioState.shared.selectedTrackID=nil;LiveStudioState.shared.selectedClipID=nil;self.syncLiveDAW();self.statusLabel.stringValue="Projekt geladen"}else{self.statusLabel.stringValue="Laden fehlgeschlagen"}}}
}
